boohoo_dwh:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      port: 5439
      user: "{{ env_var('REDSHIFT_USER', 'admin') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      dbname: boohoo_dwh
      schema: raw
      threads: 4
