name: 'boohoo_dwh'
version: '1.0.0'

profile: 'boohoo_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  boohoo_dwh:
    rdl:
      +materialized: view
      +schema: rdl
      boohoo_commerce:
        +schema: rdl_boohoo_commerce
      salesforce_commerce:
        +schema: rdl_salesforce_commerce
      shopify:
        +schema: rdl_shopify
      magento:
        +schema: rdl_magento
      oracle_commerce:
        +schema: rdl_oracle_commerce
      marketing:
        +schema: rdl_marketing
        +tags: ['marketing']
    odl:
      +materialized: table
      +schema: odl
    adl:
      +materialized: table
      +schema: bi

