boohoo_dwh:
  target: dev
  outputs:
    dev:
      type: redshift
      host: bellosdata.332779204498.eu-west-2.redshift-serverless.amazonaws.com
      port: 5439
      user: admin
      password: "B00h00Dwh!2026x"
      dbname: boohoo_dwh
      schema: public
      threads: 4
